server:
  port: 25000
spring:
  #Nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8080
        #控制台的port
        port: 8719
  application:
    name: gulimall-seckill
  #配置Redis缓存
  redis:
    host: 121.196.36.170
    port: 6379
  #整合Spring Session 指定session是存到redis里
  session:
    store-type: redis
  #spring给我们配的线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  #配置rabbitmq
  rabbitmq:
    host: 121.196.36.170
    port: 5672
    virtual-host: /
    #开启发送端确认 发送的过程中
    publisher-confirms: true
    #开启发送端确认 抵达队列
    publisher-returns: true
    template:
      #抵达队列，以异步模式优先回调组合ReturnCallback
      mandatory: true
    listener:
      simple:
        #手动ack消息 手动确认收货 手动确认模式 防止消息丢失
        acknowledge-mode: manual
  #关闭thymeleaf缓存 开发期间就能看到实时效果；上线以后就要打开缓存了(效果不大)
  thymeleaf:
    cache: false
    #cache: true
  #配置Zipkin链路追踪可视化展示
#  zipkin:
#    base-url: http://10.211.55.3:9411/
#    #关闭自己的服务发现功能
#    discovery-client-enabled: false
#    sender:
#      #设置采用http的方式
#      type: web
#  sleuth:
#    sampler:
#      #配置sleuth采样器 100%
#      probability: 1


logging:
  level:
    #上线后，可以降低日志级别
    #openfeign链路追踪
    org.springframework.cloud.openfeign: debug
    #sleuth链路追踪
    org.springframework.cloud.sleuth: debug

#management.endpoints.web.exposure.include=*
##配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all

##开启feign sentinel 熔断保护
feign:
  sentinel:
    enabled: true