server:
  port: 11000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.196.36.170:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
  cloud:
    #配置nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #配置sentinel
    sentinel:
      transport:
        dashboard: localhost:8080
        #控制台的port
        port: 8719
  #    alibaba:
  #      seata:
  #        tx-service-group: gulimall-ware-fescar-service-group
  application:
    name: gulimall-ware
  #    时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #配置rabbitmq
  rabbitmq:
    host: 121.196.36.170
    port: 5672
    virtual-host: /
    #开启发送端确认 发送的过程中
    publisher-confirms: true
    #开启发送端确认 抵达队列
    publisher-returns: true
    template:
      #抵达队列，以异步模式优先回调组合ReturnCallback
      mandatory: true
    listener:
      simple:
        #手动ack消息 手动确认收货 手动确认模式 防止消息丢失
        acknowledge-mode: manual
  #配置Zipkin链路追踪可视化展示
  zipkin:
    base-url: http://121.196.36.170:9411/
    #关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      #设置采用http的方式
      type: web
  sleuth:
    sampler:
      #配置sleuth采样器 100%
      probability: 1

mybatis-plus:
  #  告诉Mybatis Plus 扫描哪里
  mapper-locations: classpath:/mapper/**/*.xml
  #  主键自增！
  global-config:
    db-config:
      id-type: auto

#打印SQL
logging:
  level:
    com.atguigu: debug
    #设置nacos-Naming客户端的日志级别
    com:
      alibaba:
        nacos:
          client:
            naming: warn

#management.endpoints.web.exposure.include=*
#配置actuator统计审计信息 配合sentinel
management:
  endpoints:
    web:
      exposure:
        include: all

#开启feign sentinel 熔断保护
feign:
  sentinel:
    enabled: true